  services:
    php:
      volumes:
        - ./app:/var/www/html
      build:
        dockerfile: php.Dockerfile
      expose:
        - "9000"
      depends_on:
        - db
      networks:
        - single-net
    db:
      volumes:
        - pgdata-volume:/var/lib/postgresql/data
      image: postgres
      env_file:
        - postgre.env
      ports:
        - "${POSTGRESQL_HOST_PORT}:5432"
      networks:
        - single-net
    nginx:
      image: nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
      ports:
        - "${NGINX_HOST_PORT}:80"
      depends_on:
        - php
      networks:
        - single-net
  volumes:
    pgdata-volume:
  networks:
    single-net:
      driver: bridge